name: Publish to IPFS
description: Publish to IPFS
branding:
  icon: upload-cloud
  color: green
inputs:
  auth:
    description: IPFS authentication
    required: false
  path:
    description: Path to publish
    required: true
  host:
    description: IPFS hostname
    required: false
    default: ipfs.epiphyte.cloud
  port:
    description: IPFS port
    required: false
    default: "443"
  protocol:
    description: IPFS protocol
    required: false
    default: https
outputs:
  cid:
    description: IPFS CID
runs:
  using: node16
  main: index.js
