name: Publish to IPFS
description: Publish to IPFS
branding:
  icon: upload-cloud
  color: green
inputs:
  path:
    description: Path to publish
    required: true
  host:
    description: IPFS hostname
    required: false
    default: ipfs.epiphytelabs.io
  port:
    description: IPFS port
    required: false
    default: "5001"
  protocol:
    description: IPFS protocol
    required: false
    default: http
outputs:
  cid:
    description: IPFS CID
runs:
  using: node16
  main: index.js
